import Head from 'next/head';
import Header from '../components/header/Header';
import { type ReactElement } from 'react';
import Footer from '../components/footer/Footer';
import Hero from '../content/hero/Hero';
import Experience from '../content/experience/Experience';
import Contact from '../content/contact/Contact';

const Home = (): ReactElement => {
  return (
    <>
      <Head>
        <title>Willber Pilares</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero />
        <Experience />
        <Contact />
        <Footer />
      </main>
    </>
  );
};

export default Home;
